<?php $employees = $block->getEmployees(); ?>

<table border="1" cellpadding="8">

    <tr>
        <th>Employee ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Address</th>
        <th>Phone Number</th>
        <th>Delete</th>
    </tr>

    <?php foreach ($employees as $employee): ?>
        <tr>

            <td><?= $block->escapeHtml($employee->getEmployeeId()) ?></td>

            <td><?= $block->escapeHtml($employee->getFirstName()) ?></td>

            <td><?= $block->escapeHtml($employee->getLastName()) ?></td>

            <td><?= $block->escapeHtml($employee->getEmailId()) ?></td>

            <td><?= $block->escapeHtml($employee->getAddress()) ?></td>

            <td><?= $block->escapeHtml($employee->getPhoneNumber()) ?></td>

            <td>
               <form method="post"
                    action="<?= $block->getUrl('mod1/index/employeetest') ?>">

                    <?= $block->getBlockHtml('formkey') ?>

                    <input
                        type="hidden"
                        name="delete_id"
                        value="<?= $employee->getId() ?>">

                    <button type="submit">
                        Delete
                    </button>

                </form>
            </td>

        </tr>

    <?php endforeach; ?>

</table>