<form method="post" action="<?= $block->getUrl('*/*/*') ?>">

    <?= $block->getBlockHtml('formkey') ?>

    <div>
        <label>First Name</label><br>
        <input
            type="text"
            name="first_name"
            maxlength="30"
            pattern="[A-Za-z]{1,30}"
            title="First name must contain only letters (up to 30 characters, no numbers or spaces)"
            required>
    </div>

    <br>

    <div>
        <label>Last Name</label><br>
        <input
            type="text"
            name="last_name"
            maxlength="30"
            pattern="[A-Za-z]{1,30}"
            title="Last name must contain only letters (up to 30 characters, no numbers or spaces)"
            required>
    </div>

    <br>

    <div>
        <label>Email</label><br>
        <input
            type="email"
            name="email_id"
            required>
    </div>

    <br>

    <div>
        <label>Address</label><br>
        <textarea
            name="address"
            rows="4"
            cols="40"
            minlength="30"
            required></textarea>
    </div>

    <br>

    <div>
        <label>Phone Number</label><br>
        <input
            type="text"
            name="phone_number"
            maxlength="10"
            pattern="[0-9]{10}"
            required>
    </div>

    <br>

    <button type="submit">
        Save
    </button>

</form>